export const BACKEND_URL = "https://purring-agency-slow.functions.on-fleek.app"

export const COUNTRIES = [
    { "countryName": "Afghanistan", "emoji": "\uD83C\uDDE6\uD83C\uDDEB" },
    { "countryName": "Albania", "emoji": "\uD83C\uDDE6\uD83C\uDDF1" },
    { "countryName": "Algeria", "emoji": "\uD83C\uDDE9\uD83C\uDDFF" },
    { "countryName": "Andorra", "emoji": "\uD83C\uDDE6\uD83C\uDDE9" },
    { "countryName": "Angola", "emoji": "\uD83C\uDDE6\uD83C\uDDF4" },
    { "countryName": "Antigua and Barbuda", "emoji": "\uD83C\uDDE6\uD83C\uDDEC" },
    { "countryName": "Argentina", "emoji": "\uD83C\uDDE6\uD83C\uDDF7" },
    { "countryName": "Armenia", "emoji": "\uD83C\uDDE6\uD83C\uDDF2" },
    { "countryName": "Australia", "emoji": "\uD83C\uDDE6\uD83C\uDDFA" },
    { "countryName": "Austria", "emoji": "\uD83C\uDDE6\uD83C\uDDF9" },
    { "countryName": "Azerbaijan", "emoji": "\uD83C\uDDE6\uD83C\uDDFF" },
    { "countryName": "Bahamas", "emoji": "\uD83C\uDDE7\uD83C\uDDF8" },
    { "countryName": "Bahrain", "emoji": "\uD83C\uDDE7\uD83C\uDDED" },
    { "countryName": "Bangladesh", "emoji": "\uD83C\uDDE7\uD83C\uDDE9" },
    { "countryName": "Barbados", "emoji": "\uD83C\uDDE7\uD83C\uDDE7" },
    { "countryName": "Belarus", "emoji": "\uD83C\uDDE7\uD83C\uDDFE" },
    { "countryName": "Belgium", "emoji": "\uD83C\uDDE7\uD83C\uDDEA" },
    { "countryName": "Belize", "emoji": "\uD83C\uDDE7\uD83C\uDDFF" },
    { "countryName": "Benin", "emoji": "\uD83C\uDDE7\uD83C\uDDEF" },
    { "countryName": "Bhutan", "emoji": "\uD83C\uDDE7\uD83C\uDDF9" },
    { "countryName": "Bolivia", "emoji": "\uD83C\uDDE7\uD83C\uDDF4" },
    { "countryName": "Bosnia and Herzegovina", "emoji": "\uD83C\uDDE7\uD83C\uDDE6" },
    { "countryName": "Botswana", "emoji": "\uD83C\uDDE7\uD83C\uDDFC" },
    { "countryName": "Brazil", "emoji": "\uD83C\uDDE7\uD83C\uDDF7" },
    { "countryName": "Brunei", "emoji": "\uD83C\uDDE7\uD83C\uDDF3" },
    { "countryName": "Bulgaria", "emoji": "\uD83C\uDDE7\uD83C\uDDEC" },
    { "countryName": "Burkina Faso", "emoji": "\uD83C\uDDE7\uD83C\uDDEB" },
    { "countryName": "Burundi", "emoji": "\uD83C\uDDE7\uD83C\uDDEE" },
    { "countryName": "Cabo Verde", "emoji": "\uD83C\uDDE8\uD83C\uDDF4" },
    { "countryName": "Cambodia", "emoji": "\uD83C\uDDF0\uD83C\uDDED" },
    { "countryName": "Cameroon", "emoji": "\uD83C\uDDE8\uD83C\uDDF2" },
    { "countryName": "Canada", "emoji": "\uD83C\uDDE8\uD83C\uDDE6" },
    { "countryName": "Central African Republic", "emoji": "\uD83C\uDDE8\uD83C\uDDEB" },
    { "countryName": "Chad", "emoji": "\uD83C\uDDE9\uD83C\uDDF1" },
    { "countryName": "Chile", "emoji": "\uD83C\uDDE8\uD83C\uDDF1" },
    { "countryName": "China", "emoji": "\uD83C\uDDE8\uD83C\uDDF3" },
    { "countryName": "Colombia", "emoji": "\uD83C\uDDE8\uD83C\uDDF4" },
    { "countryName": "Comoros", "emoji": "\uD83C\uDDF0\uD83C\uDDF2" },
    { "countryName": "Congo (Congo-Brazzaville)", "emoji": "\uD83C\uDDE8\uD83C\uDDEC" },
    { "countryName": "Costa Rica", "emoji": "\uD83C\uDDE8\uD83C\uDDF7" },
    { "countryName": "Croatia", "emoji": "\uD83C\uDDED\uD83C\uDDF7" },
    { "countryName": "Cuba", "emoji": "\uD83C\uDDE8\uD83C\uDDFA" },
    { "countryName": "Cyprus", "emoji": "\uD83C\uDDE8\uD83C\uDDFE" },
    { "countryName": "Czechia", "emoji": "\uD83C\uDDE8\uD83C\uDDFF" },
    { "countryName": "Denmark", "emoji": "\uD83C\uDDE9\uD83C\uDDF0" },
    { "countryName": "Djibouti", "emoji": "\uD83C\uDDE9\uD83C\uDDEF" },
    { "countryName": "Dominica", "emoji": "\uD83C\uDDE9\uD83C\uDDF2" },
    { "countryName": "Dominican Republic", "emoji": "\uD83C\uDDE9\uD83C\uDDF4" },
    { "countryName": "Ecuador", "emoji": "\uD83C\uDDEA\uD83C\uDDE8" },
    { "countryName": "Egypt", "emoji": "\uD83C\uDDEA\uD83C\uDDEC" },
    { "countryName": "El Salvador", "emoji": "\uD83C\uDDF8\uD83C\uDDFB" },
    { "countryName": "Equatorial Guinea", "emoji": "\uD83C\uDDEC\uD83C\uDDF6" },
    { "countryName": "Eritrea", "emoji": "\uD83C\uDDEA\uD83C\uDDF7" },
    { "countryName": "Estonia", "emoji": "\uD83C\uDDEA\uD83C\uDDEA" },
    { "countryName": "Eswatini", "emoji": "\uD83C\uDDF8\uD83C\uDDFF" },
    { "countryName": "Ethiopia", "emoji": "\uD83C\uDDEA\uD83C\uDDF9" },
    { "countryName": "Fiji", "emoji": "\uD83C\uDDEB\uD83C\uDDEF" },
    { "countryName": "Finland", "emoji": "\uD83C\uDDEB\uD83C\uDDEE" },
    { "countryName": "France", "emoji": "\uD83C\uDDEB\uD83C\uDDF7" },
    { "countryName": "Gabon", "emoji": "\uD83C\uDDEC\uD83C\uDDE6" },
    { "countryName": "Gambia", "emoji": "\uD83C\uDDEC\uD83C\uDDF2" },
    { "countryName": "Georgia", "emoji": "\uD83C\uDDEC\uD83C\uDDEA" },
    { "countryName": "Germany", "emoji": "\uD83C\uDDE9\uD83C\uDDEA" },
    { "countryName": "Ghana", "emoji": "\uD83C\uDDEC\uD83C\uDDED" },
    { "countryName": "Greece", "emoji": "\uD83C\uDDEC\uD83C\uDDF7" },
    { "countryName": "Grenada", "emoji": "\uD83C\uDDEC\uD83C\uDDE9" },
    { "countryName": "Guatemala", "emoji": "\uD83C\uDDEC\uD83C\uDDF9" },
    { "countryName": "Guinea", "emoji": "\uD83C\uDDEC\uD83C\uDDF3" },
    { "countryName": "Guinea-Bissau", "emoji": "\uD83C\uDDEC\uD83C\uDDFC" },
    { "countryName": "Guyana", "emoji": "\uD83C\uDDEC\uD83C\uDDFE" },
    { "countryName": "Haiti", "emoji": "\uD83C\uDDED\uD83C\uDDF9" },
    { "countryName": "Honduras", "emoji": "\uD83C\uDDED\uD83C\uDDF3" },
    { "countryName": "Hungary", "emoji": "\uD83C\uDDED\uD83C\uDDFA" },
    { "countryName": "Iceland", "emoji": "\uD83C\uDDEE\uD83C\uDDF8" },
    { "countryName": "India", "emoji": "\uD83C\uDDEE\uD83C\uDDF3" },
    { "countryName": "Indonesia", "emoji": "\uD83C\uDDEE\uD83C\uDDE9" },
    { "countryName": "Iran", "emoji": "\uD83C\uDDEE\uD83C\uDDF7" },
    { "countryName": "Iraq", "emoji": "\uD83C\uDDEE\uD83C\uDDF6" },
    { "countryName": "Ireland", "emoji": "\uD83C\uDDEE\uD83C\uDDEA" },
    { "countryName": "Israel", "emoji": "\uD83C\uDDEE\uD83C\uDDF1" },
    { "countryName": "Italy", "emoji": "\uD83C\uDDEE\uD83C\uDDF9" },
    { "countryName": "Jamaica", "emoji": "\uD83C\uDDEF\uD83C\uDDF2" },
    { "countryName": "Japan", "emoji": "\uD83C\uDDEF\uD83C\uDDF5" },
    { "countryName": "Jordan", "emoji": "\uD83C\uDDEF\uD83C\uDDF4" },
    { "countryName": "Kazakhstan", "emoji": "\uD83C\uDDF0\uD83C\uDDFF" },
    { "countryName": "Kenya", "emoji": "\uD83C\uDDF0\uD83C\uDDEA" },
    { "countryName": "Kiribati", "emoji": "\uD83C\uDDF0\uD83C\uDDEE" },
    { "countryName": "Kuwait", "emoji": "\uD83C\uDDF0\uD83C\uDDFC" },
    { "countryName": "Kyrgyzstan", "emoji": "\uD83C\uDDF0\uD83C\uDDEC" },
    { "countryName": "Laos", "emoji": "\uD83C\uDDF1\uD83C\uDDE6" },
    { "countryName": "Latvia", "emoji": "\uD83C\uDDF1\uD83C\uDDFB" },
    { "countryName": "Lebanon", "emoji": "\uD83C\uDDF1\uD83C\uDDE7" },
    { "countryName": "Lesotho", "emoji": "\uD83C\uDDF1\uD83C\uDDF8" },
    { "countryName": "Liberia", "emoji": "\uD83C\uDDF1\uD83C\uDDF7" },
    { "countryName": "Libya", "emoji": "\uD83C\uDDF1\uD83C\uDDFE" },
    { "countryName": "Liechtenstein", "emoji": "\uD83C\uDDF1\uD83C\uDDEE" },
    { "countryName": "Lithuania", "emoji": "\uD83C\uDDF1\uD83C\uDDF9" },
    { "countryName": "Luxembourg", "emoji": "\uD83C\uDDF1\uD83C\uDDFA" },
    { "countryName": "Madagascar", "emoji": "\uD83C\uDDF2\uD83C\uDDEC" },
    { "countryName": "Malawi", "emoji": "\uD83C\uDDF2\uD83C\uDDFC" },
    { "countryName": "Malaysia", "emoji": "\uD83C\uDDF2\uD83C\uDDFE" },
    { "countryName": "Maldives", "emoji": "\uD83C\uDDF2\uD83C\uDDFB" },
    { "countryName": "Mali", "emoji": "\uD83C\uDDF2\uD83C\uDDF1" },
    { "countryName": "Malta", "emoji": "\uD83C\uDDF2\uD83C\uDDF9" },
    { "countryName": "Marshall Islands", "emoji": "\uD83C\uDDF2\uD83C\uDDED" },
    { "countryName": "Mauritania", "emoji": "\uD83C\uDDF2\uD83C\uDDF7" },
    { "countryName": "Mauritius", "emoji": "\uD83C\uDDF2\uD83C\uDDFA" },
    { "countryName": "Mexico", "emoji": "\uD83C\uDDF2\uD83C\uDDFD" },
    { "countryName": "Micronesia", "emoji": "\uD83C\uDDEB\uD83C\uDDED" },
    { "countryName": "Moldova", "emoji": "\uD83C\uDDF2\uD83C\uDDE9" },
    { "countryName": "Monaco", "emoji": "\uD83C\uDDF2\uD83C\uDDE8" },
    { "countryName": "Mongolia", "emoji": "\uD83C\uDDF2\uD83C\uDDF3" },
    { "countryName": "Montenegro", "emoji": "\uD83C\uDDF2\uD83C\uDDEA" },
    { "countryName": "Morocco", "emoji": "\uD83C\uDDF2\uD83C\uDDE6" },
    { "countryName": "Mozambique", "emoji": "\uD83C\uDDF2\uD83C\uDDFF" },
    { "countryName": "Myanmar (Burma)", "emoji": "\uD83C\uDDF2\uD83C\uDDF2" },
    { "countryName": "Namibia", "emoji": "\uD83C\uDDF3\uD83C\uDDE6" },
    { "countryName": "Nauru", "emoji": "\uD83C\uDDF3\uD83C\uDDF7" },
    { "countryName": "Nepal", "emoji": "\uD83C\uDDF3\uD83C\uDDF5" },
    { "countryName": "Netherlands", "emoji": "\uD83C\uDDF3\uD83C\uDDF1" },
    { "countryName": "New Zealand", "emoji": "\uD83C\uDDF3\uD83C\uDDFF" },
    { "countryName": "Nicaragua", "emoji": "\uD83C\uDDF3\uD83C\uDDEE" },
    { "countryName": "Niger", "emoji": "\uD83C\uDDF3\uD83C\uDDEA" },
    { "countryName": "Nigeria", "emoji": "\uD83C\uDDF3\uD83C\uDDEC" },
    { "countryName": "North Korea", "emoji": "\uD83C\uDDF0\uD83C\uDDF5" },
    { "countryName": "North Macedonia", "emoji": "\uD83C\uDDF2\uD83C\uDDF0" },
    { "countryName": "Norway", "emoji": "\uD83C\uDDF3\uD83C\uDDF4" },
    { "countryName": "Oman", "emoji": "\uD83C\uDDF4\uD83C\uDDF2" },
    { "countryName": "Pakistan", "emoji": "\uD83C\uDDF5\uD83C\uDDF0" },
    { "countryName": "Palau", "emoji": "\uD83C\uDDF5\uD83C\uDDFC" },
    { "countryName": "Palestine", "emoji": "\uD83C\uDDF5\uD83C\uDDF8" },
    { "countryName": "Panama", "emoji": "\uD83C\uDDF5\uD83C\uDDE6" },
    { "countryName": "Papua New Guinea", "emoji": "\uD83C\uDDF5\uD83C\uDDEC" },
    { "countryName": "Paraguay", "emoji": "\uD83C\uDDF5\uD83C\uDDFE" },
    { "countryName": "Peru", "emoji": "\uD83C\uDDF5\uD83C\uDDEA" },
    { "countryName": "Philippines", "emoji": "\uD83C\uDDF5\uD83C\uDDED" },
    { "countryName": "Poland", "emoji": "\uD83C\uDDF5\uD83C\uDDF1" },
    { "countryName": "Portugal", "emoji": "\uD83C\uDDF5\uD83C\uDDF9" },
    { "countryName": "Qatar", "emoji": "\uD83C\uDDF6\uD83C\uDDE6" },
    { "countryName": "Romania", "emoji": "\uD83C\uDDF7\uD83C\uDDF4" },
    { "countryName": "Russia", "emoji": "\uD83C\uDDF7\uD83C\uDDFA" },
    { "countryName": "Rwanda", "emoji": "\uD83C\uDDF7\uD83C\uDDFC" },
    { "countryName": "Saint Kitts and Nevis", "emoji": "\uD83C\uDDF0\uD83C\uDDF3" },
    { "countryName": "Saint Lucia", "emoji": "\uD83C\uDDF1\uD83C\uDDE8" },
    { "countryName": "Saint Vincent and the Grenadines", "emoji": "\uD83C\uDDFB\uD83C\uDDE8" },
    { "countryName": "Samoa", "emoji": "\uD83C\uDDFC\uD83C\uDDF8" },
    { "countryName": "San Marino", "emoji": "\uD83C\uDDF8\uD83C\uDDF2" },
    { "countryName": "Sao Tome and Principe", "emoji": "\uD83C\uDDF8\uD83C\uDDF9" },
    { "countryName": "Saudi Arabia", "emoji": "\uD83C\uDDF8\uD83C\uDDE6" },
    { "countryName": "Senegal", "emoji": "\uD83C\uDDF8\uD83C\uDDF3" },
    { "countryName": "Serbia", "emoji": "\uD83C\uDDF7\uD83C\uDDF8" },
    { "countryName": "Seychelles", "emoji": "\uD83C\uDDF8\uD83C\uDDE8" },
    { "countryName": "Sierra Leone", "emoji": "\uD83C\uDDF8\uD83C\uDDF1" },
    { "countryName": "Singapore", "emoji": "\uD83C\uDDF8\uD83C\uDDEC" },
    { "countryName": "Slovakia", "emoji": "\uD83C\uDDF8\uD83C\uDDF0" },
    { "countryName": "Slovenia", "emoji": "\uD83C\uDDF8\uD83C\uDDEE" },
    { "countryName": "Solomon Islands", "emoji": "\uD83C\uDDF8\uD83C\uDDE7" },
    { "countryName": "Somalia", "emoji": "\uD83C\uDDF8\uD83C\uDDF4" },
    { "countryName": "South Africa", "emoji": "\uD83C\uDDFF\uD83C\uDDE6" },
    { "countryName": "South Korea", "emoji": "\uD83C\uDDF0\uD83C\uDDF7" },
    { "countryName": "South Sudan", "emoji": "\uD83C\uDDF8\uD83C\uDDF8" },
    { "countryName": "Spain", "emoji": "\uD83C\uDDEA\uD83C\uDDF8" },
    { "countryName": "Sri Lanka", "emoji": "\uD83C\uDDF1\uD83C\uDDF0" },
    { "countryName": "Sudan", "emoji": "\uD83C\uDDF8\uD83C\uDDE9" },
    { "countryName": "Suriname", "emoji": "\uD83C\uDDF8\uD83C\uDDF7" },
    { "countryName": "Sweden", "emoji": "\uD83C\uDDF8\uD83C\uDDEA" },
    { "countryName": "Switzerland", "emoji": "\uD83C\uDDE8\uD83C\uDDED" },
    { "countryName": "Syria", "emoji": "\uD83C\uDDF8\uD83C\uDDFE" },
    { "countryName": "Taiwan", "emoji": "\uD83C\uDDF9\uD83C\uDDFC" },
    { "countryName": "Tajikistan", "emoji": "\uD83C\uDDF9\uD83C\uDDEF" },
    { "countryName": "Tanzania", "emoji": "\uD83C\uDDF9\uD83C\uDDFF" },
    { "countryName": "Thailand", "emoji": "\uD83C\uDDF9\uD83C\uDDED" },
    { "countryName": "Timor-Leste", "emoji": "\uD83C\uDDF9\uD83C\uDDF1" },
    { "countryName": "Togo", "emoji": "\uD83C\uDDFA\uD83C\uDDEC" },
    { "countryName": "Tonga", "emoji": "\uD83C\uDDF9\uD83C\uDDF4" },
    { "countryName": "Trinidad and Tobago", "emoji": "\uD83C\uDDF9\uD83C\uDDF9" },
    { "countryName": "Tunisia", "emoji": "\uD83C\uDDF9\uD83C\uDDF3" },
    { "countryName": "Turkey", "emoji": "\uD83C\uDDF9\uD83C\uDDF7" },
    { "countryName": "Turkmenistan", "emoji": "\uD83C\uDDF9\uD83C\uDDF2" },
    { "countryName": "Tuvalu", "emoji": "\uD83C\uDDF9\uD83C\uDDFB" },
    { "countryName": "Uganda", "emoji": "\uD83C\uDDFA\uD83C\uDDEC" },
    { "countryName": "Ukraine", "emoji": "\uD83C\uDDFA\uD83C\uDDE6" },
    { "countryName": "United Arab Emirates", "emoji": "\uD83C\uDDF5\uD83C\uDDF8" },
    { "countryName": "United Kingdom", "emoji": "\uD83C\uDDEC\uD83C\uDDE7" },
    { "countryName": "United States", "emoji": "\uD83C\uDDFA\uD83C\uDDF8" },
    { "countryName": "Uruguay", "emoji": "\uD83C\uDDFA\uD83C\uDDFE" },
    { "countryName": "Uzbekistan", "emoji": "\uD83C\uDDFA\uD83C\uDDFF" },
    { "countryName": "Vanuatu", "emoji": "\uD83C\uDDFB\uD83C\uDDFA" },
    { "countryName": "Vatican City", "emoji": "\uD83C\uDDFB\uD83C\uDDE6" },
    { "countryName": "Venezuela", "emoji": "\uD83C\uDDFB\uD83C\uDDEA" },
    { "countryName": "Vietnam", "emoji": "\uD83C\uDDFB\uD83C\uDDF3" },
    { "countryName": "Yemen", "emoji": "\uD83C\uDDFE\uD83C\uDDEA" },
    { "countryName": "Zambia", "emoji": "\uD83C\uDDFF\uD83C\uDDF2" },
    { "countryName": "Zimbabwe", "emoji": "\uD83C\uDDFF\uD83C\uDDFC" }
  ];